### ISSUE TITLE
expected audience error

### ISSUE THREAD

**Issue by rzal** [weinong/k8s-dashboard-with-aks-aad#1]
Hi Weinong

I was really glad to find your guide to setup oauth2-proxy to work with AKS with Managed ADD enabled, so thanks.

I've got a slight issue with the setup however, I think I've configured everything as per your instructions, but I still get error.

The only extra param is the `cookie-secure=true` but I guess that can't hurt. Can you see what I'm doing wrong?

Using oauth2-proxy image: `quay.io/oauth2-proxy/oauth2-proxy:v7.1.2` 

Error:
```
[2021/04/15 13:37:11] [azure.go:165] unable to get email claim from id_token: <nil>
[2021/04/15 13:37:11] [azure.go:235] unable to verify token: oidc: expected audience "abcdefsg-abcd-4ebe-8928-22ce8a0790d4" got ["6dae42f8-4368-4678-94ff-3960e28e3630"]
[2021/04/15 13:37:11] [azure.go:173] unable to get email claim from access token: <nil>
[2021/04/15 13:37:11] [oauthproxy.go:794] Error creating session during OAuth2 callback: unable to get email address: unexpected status "401": {
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token validation failure. Invalid audience.",
    "innerError": {
      "date": "2021-04-15T13:37:11",
      "request-id": "8b5a1fad-daa1-4860-b929-7a57eeaed2ae",
      "client-request-id": "8b5a1fad-daa1-4860-b929-7a57eeaed2ae"
    }
  }
}
```

```
        - --provider=azure
        - --oidc-issuer-url=https://sts.windows.net/a8447452-abcd-4ebb-ab1f-7d3553af4f66/
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        - --azure-tenant=a8447452-abcd-4ebb-ab1f-7d3553af4f66
        - --client-id=abcdefsg-abcd-4ebe-8928-22ce8a0790d4
        - --client-secret=KaP-q54ghq45huy45hhhh-kU-2Fu9e_Li6
        - --cookie-secret="CI0PT2g!GO4oEA12$%GHATHRH^%JUa"
        - --pass-access-token=true
        - --resource=6dae42f8-4368-4678-94ff-3960e28e3630
        - --set-xauthrequest=true
        # extra
        - --cookie-secure=true

```
abcdefsg-abcd-4ebe-8928-22ce8a0790d4 API permissions and Auth settings

![image](https://user-images.githubusercontent.com/26010553/114890291-ca888580-9e02-11eb-9337-d1e988c854f5.png)
![image](https://user-images.githubusercontent.com/26010553/114890472-f277e900-9e02-11eb-9bb1-59f40f2bcb33.png)

Thanks!

# UPDATE #1
It seems the Voyager Ingress controller oauth2 feature doesn't support access tokens, I have managed to get my setup working with Nginx Ingress Controller. 

```
    rules:
      # Dashboard proxied to Nginx Ingress (no LB IP used)
      - host: "{{ include \"defaultDashboard\" . }}"
        http:
          paths:
            - backend:
                serviceName: ingress-nginx-controller.namespace
                servicePort: 80
              path: /
````

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: 'X-Auth-Request-Access-Token'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $token $upstream_http_x_auth_request_access_token;
      proxy_set_header Authorization "Bearer $token";
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: external-auth-oauth2
  namespace: kubernetes-dashboard
spec:
  rules:
  - host: aks-westeu-1.example.com
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 80
        path: /
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
spec:
  rules:
  - host: aks-westeu-1.example.com
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy-dashboard
          servicePort: 4180
        path: /oauth2
```

Using NodePort on the Nginx ingress so it can work behind HAProxy for the Dashboard SSO

```
# Source: ingress-nginx/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    helm.sh/chart: ingress-nginx-3.27.0
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 0.45.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: nuvola-system
spec:
  type: NodePort
```
