### ISSUE TITLE
V2 Azure Auth

### ISSUE THREAD

**Issue by vittoriocanilli** [weinong/k8s-dashboard-with-aks-aad#2]
Hello Weinong,

your setup worked perfectly for our AKS clusters till the version **7.2.0** of OAuth2, but now we want to update it to the version **7.4.0**, which apparently requires _V2 Azure Auth_.

I looks like I have to change the value of the `--oidc-issuer-url` from `https://sts.windows.net/<your-AAD-tenant-id>/` to `https://login.microsoftonline.com/<your-AAD-tenant-id>/v2.0`, but after the successful login on the AKS cluster I can not access the resources that my AAD groups grant me to see.

It looks like I have to change the value of the `--resource` argument to something different than `6dae42f8-4368-4678-94ff-3960e28e3630`, but I did not find any working value as solution so far.

Did you have any chance to try this new version? Thanks in advance!

**Comment by netanel-sayada** [comment]
was also looking for this fix.
there is tons of issues about this on oauth2-proxy

**Comment by imranrazakhan** [comment]
@vittoriocanilli  @netanel-sayada  I am also evaluating these options, I think with new changes we don't need to mention oidc_url, As if we mention provider=azure, it will automatically handle endpoint

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        args:
        - "--http-address=0.0.0.0:4180"
        - "--oauth-redirect-url=https://oauth2-proxy.example.com/oauth2/callback"
        - "--upstream=http://kubernetes-dashboard:8080"
        - "--email-domain=example.com"
        - "--provider=azure"
        - "--client-id=YOUR_AZURE_AD_CLIENT_ID"
        - "--client-secret=YOUR_AZURE_AD_CLIENT_SECRET"
        - "--cookie-secret=YOUR_COOKIE_SECRET"
        ports:
        - containerPort: 4180

```
